name: Fetch, Process, and Publish Subtitles

on:
  schedule:
    - cron: '0 0 * * *' # 上海/台北時間上午 8:00
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 簽出當前倉庫 (yt-sub) 的程式碼
      - name: Checkout yt-sub repository
        uses: actions/checkout@v4

      # 2. 設定 Python 環境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. 安裝所有需要的 Python 套件
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 寫入 Cookies 文件
      - name: Write cookies to file
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      # 5. 執行核心腳本 (下載字幕、AI處理、保存為 .md 文件)
      - name: Run Python script for fetching and processing
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python fetch_subtitles.py

      # 6. 將處理好的文章推送到 010news 倉庫
      - name: Push processed articles to 010news repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          source-directory: 'processed_articles'
          destination-github-username: 'hendrywu2020'
          destination-repository-name: '010news'
          commit-message: 'feat: Add new daily article'
          target-branch: main
