name: Fetch YouTube Subtitles Daily

on:
  schedule:
    - cron: '0 0 * * *' # 上海/台北時間上午 8:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # --- 新增的區塊：授予工作流程寫入權限 ---
    permissions:
      contents: write
    # ------------------------------------------

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write cookies to file
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Run subtitle fetcher script
        env:
          YOUTUBE_CHANNEL_ID: ${{ secrets.YOUTUBE_CHANNEL_ID }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python fetch_subtitles.py

      - name: Commit and push subtitles
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Add new subtitles"
          file_pattern: "subtitles/*.srv3"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions Bot <actions@github.com>"
